// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

using System;
using System.Collections.Generic;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace SWP_TV_Projekt
{
    public partial class TvProgram
    {
        [JsonProperty("data")] public List<Datum> Data { get; set; }
    }

    public class Datum
    {
        [JsonProperty("channel_id")] public long ChannelId { get; set; }

        [JsonProperty("entries")] public List<Entry> Entries { get; set; }
    }

    public class Entry
    {
        [JsonProperty("id")] public string Id { get; set; }

        [JsonProperty("start")] public DateTimeOffset Start { get; set; }

        [JsonProperty("end")] public DateTimeOffset End { get; set; }

        [JsonProperty("title")] public string Title { get; set; }

        [JsonProperty("category")] public string Category { get; set; }

        [JsonProperty("description")] public string Description { get; set; }

        [JsonProperty("photo")] public Uri Photo { get; set; }
    }

    public partial class TvProgram
    {
        public static TvProgram FromJson(string json)
        {
            return JsonConvert.DeserializeObject<TvProgram>(json, Converter.Settings);
        }
    }

    public static class Serialize
    {
        public static string ToJson(this TvProgram self)
        {
            return JsonConvert.SerializeObject(self, Converter.Settings);
        }
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter {DateTimeStyles = DateTimeStyles.AssumeUniversal}
            }
        };
    }
}